junit:
<<<<<<< HEAD
  stage: test
  script:
    - cd SENG202_Project
    - mvn -B clean test
generate_artifacts:
  stage: deploy
  script:
    - mvn -B clean site package
  artifacts:
    paths:
    - target/s202*.jar
=======
stage: test
script:
- mvn -B clean test
generate_artifacts:
stage: deploy
script:
- mvn -B clean site package
artifacts:
paths:
- target/s202*.jar
>>>>>>> bc19b880... Added CI file
